/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import java.awt.*;
import java.awt.geom.Path2D;
import javax.swing.*;
/**
 *
 * @author Higor
 */
public class Cadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicial.class.getName());

    /**
     * Creates new form TelaInicial
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        lbCadastreSe = new javax.swing.JLabel();
        lbEmailCadastro = new javax.swing.JLabel();
        txtEmailCadastro = new javax.swing.JTextField();
        lbSenhaCadastro = new javax.swing.JLabel();
        txtSenhaCadastro = new javax.swing.JPasswordField();
        btCadastroCadastro = new javax.swing.JButton();
        lbTConta = new javax.swing.JLabel();
        btLoginCadastro = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbSobrenome = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JFormattedTextField();
        lbNascimento = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        lbSenhaCadastro1 = new javax.swing.JLabel();
        txtSenhaCadastro1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setResizable(false);

        jLayeredPane2.setBackground(new java.awt.Color(176, 0, 0));
        jLayeredPane2.setOpaque(true);

        lbCadastreSe.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        lbCadastreSe.setForeground(new java.awt.Color(255, 255, 255));
        lbCadastreSe.setText("Cadastre - se");

        lbEmailCadastro.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        lbEmailCadastro.setForeground(new java.awt.Color(255, 255, 255));
        lbEmailCadastro.setText("Email");

        lbSenhaCadastro.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        lbSenhaCadastro.setForeground(new java.awt.Color(255, 255, 255));
        lbSenhaCadastro.setText("Senha");

        btCadastroCadastro.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        btCadastroCadastro.setForeground(new java.awt.Color(204, 0, 0));
        btCadastroCadastro.setText("Cadastre-se");
        btCadastroCadastro.setOpaque(true);
        btCadastroCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroCadastroActionPerformed(evt);
            }
        });

        lbTConta.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        lbTConta.setForeground(new java.awt.Color(255, 255, 255));
        lbTConta.setText("Já Tem uma conta?");

        btLoginCadastro.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        btLoginCadastro.setForeground(new java.awt.Color(204, 0, 0));
        btLoginCadastro.setText("Fazer Login");

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setOpaque(true);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel6)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        lbNome.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        lbNome.setForeground(new java.awt.Color(255, 255, 255));
        lbNome.setText("Nome");

        lbSobrenome.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        lbSobrenome.setForeground(new java.awt.Color(255, 255, 255));
        lbSobrenome.setText("Sobrenome");

        txtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtNascimento.setText("DD/MM/AAAA");

        lbNascimento.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        lbNascimento.setForeground(new java.awt.Color(255, 255, 255));
        lbNascimento.setText("Nascimento");

        lbSenhaCadastro1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        lbSenhaCadastro1.setForeground(new java.awt.Color(255, 255, 255));
        lbSenhaCadastro1.setText("Repita a senha");

        jLayeredPane2.setLayer(lbCadastreSe, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lbEmailCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtEmailCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lbSenhaCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtSenhaCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btCadastroCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lbTConta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btLoginCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lbNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lbSobrenome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtNascimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lbNascimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtSobrenome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lbSenhaCadastro1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtSenhaCadastro1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSenhaCadastro1)
                                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane2Layout.createSequentialGroup()
                                            .addComponent(lbSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(41, 41, 41)
                                            .addComponent(txtSenhaCadastro))
                                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbSobrenome)
                                                        .addComponent(lbNascimento))
                                                    .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(18, 18, 18)
                                            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtEmailCadastro)
                                                .addComponent(txtNome)
                                                .addComponent(txtNascimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                                .addComponent(txtSobrenome))))))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(lbCadastreSe)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(btCadastroCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbTConta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(btLoginCadastro)))
                                    .addGap(4, 4, 4)))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(txtSenhaCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(102, 102, 102))))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(lbCadastreSe)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSobrenome)
                    .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmailCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSenhaCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenhaCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSenhaCadastro1))
                .addGap(7, 7, 7)
                .addComponent(btCadastroCadastro)
                .addGap(45, 45, 45)
                .addComponent(lbTConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLoginCadastro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastroCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastroCadastroActionPerformed

public class RoundedRightPanel extends JPanel {
    private int arc = 40; // how round the right corners are

    public RoundedRightPanel() {
        setOpaque(false); // keeps corners transparent
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int w = getWidth();
        int h = getHeight();

        // Path with only top-right & bottom-right corners rounded
        Path2D.Double shape = new Path2D.Double();
        shape.moveTo(0, 0);              // top-left
        shape.lineTo(w - arc, 0);
        shape.quadTo(w, 0, w, arc);      // top-right curve
        shape.lineTo(w, h - arc);
        shape.quadTo(w, h, w - arc, h);  // bottom-right curve
        shape.lineTo(0, h);
        shape.closePath();

        // Fill the panel background
        g2.setColor(getBackground());
        g2.fill(shape);

        g2.dispose();
    }
}
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastroCadastro;
    private javax.swing.JButton btLoginCadastro;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel lbCadastreSe;
    private javax.swing.JLabel lbEmailCadastro;
    private javax.swing.JLabel lbNascimento;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSenhaCadastro;
    private javax.swing.JLabel lbSenhaCadastro1;
    private javax.swing.JLabel lbSobrenome;
    private javax.swing.JLabel lbTConta;
    private javax.swing.JTextField txtEmailCadastro;
    private javax.swing.JFormattedTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenhaCadastro;
    private javax.swing.JPasswordField txtSenhaCadastro1;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
